framework:
  cache:
    # Unique name of your app: used to compute stable namespaces for cache keys.
    #prefix_seed: your_vendor_name/app_name

    # The "app" cache stores to the filesystem by default.
    # The data in this cache should persist between deploys.
    # Other options include:

    # Redis
    app: cache.adapter.redis
    default_redis_provider: '%env(REDIS_DSN)%'

    pools:
      doctrine.result_cache_pool:
        adapter: cache.adapter.redis

      doctrine.system_cache_pool:
        adapter: cache.adapter.redis

      doctrine.metadata_cache_pool:
        adapter: cache.adapter.redis
