old_sound_rabbit_mq:
  connections:
    default:
      url: '%env(RABBITMQ_URL)%'
  producers:
    recalculate_skills_for_user:
      connection: default
      exchange_options: { name: 'old_sound_rabbit_mq.recalculate_skills_for_user', type: direct }
  consumers:
    recalculate_skills_for_user:
      connection: default
      exchange_options: { name: 'old_sound_rabbit_mq.recalculate_skills_for_user', type: direct }
      queue_options: { name: 'old_sound_rabbit_mq.consumer.recalculate_skills_for_user' }
      callback: App\Consumer\RecalculateSkillsForUser\Consumer
      idle_timeout: 300
      idle_timeout_exit_code: 0
      graceful_max_execution:
        timeout: 1800
        exit_code: 0
      qos_options: { prefetch_size: 0, prefetch_count: 1, global: false }
