version: '3.7'

services:

  php-fpm:
    build: docker
    working_dir: /app
    environment:
      - PHP_IDE_CONFIG=serverName=student-storage-progress-service
    ports:
      - '9000:9000'
    volumes:
      - ./:/app
      - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    networks:
      student-storage-progress:
        ipv4_address: 172.100.0.2

  nginx:
    image: nginx
    working_dir: /app
    ports:
      - '7773:80'
    volumes:
      - ./:/app
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
    networks:
      student-storage-progress:
        ipv4_address: 172.100.0.3

  postgres:
    image: postgres:15
    ports:
      - "15432:5432"
    working_dir: /app
    #        restart:     always
    environment:
      POSTGRES_DB: 'student_storage_progress'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
    volumes:
      - dump:/app/dump
      - postgresql:/var/lib/postgresql/data
    networks:
      student-storage-progress:
        ipv4_address: 172.100.0.4

volumes:
  dump:
  postgresql:

networks:
  student-storage-progress:
    ipam:
      driver: default
      config:
        - subnet: 172.100.0.0/24
