version: '3.7'

services:

    php-fpm:
        build:       docker
        ports:
            - '9000:9000'
        volumes:
            - ./:/app
        working_dir: /app

    nginx:
        image:       nginx
        working_dir: /app
        ports:
            - '7773:80'
        volumes:
            - ./:/app
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        links:
            - php-fpm

    postgres:
        image:       postgres:15
        ports:
            - 15432:5432
        working_dir: /app
        restart:     always
        environment:
            POSTGRES_DB:       'student_storage_progress'
            POSTGRES_USER:     'user'
            POSTGRES_PASSWORD: 'password'
        volumes:
            - dump:/app/dump
            - postgresql:/var/lib/postgresql/data

volumes:
    dump:
    postgresql:
